[[handlers]]
name = "YouTube"
pattern = "https://[m.]?youtube.com/watch\?v\="
command = ["yt-dlp", "{url}"]

[[handlers]]
name = "BitTorrent"
pattern = "magnet:"
command = ["torrent", "{url}"]

[[handlers]]
name = "BBC Sounds Series"
pattern = "https://www.bbc.co.uk/sounds/series/"
command = ["get_iplayer", "-g", "--pid-recursive", "{url}" ]

[[handlers]]
name = "BBC iPlayer"
pattern = "bbc.co.uk/iplayer"
command = ["get_iplayer", "-g", "{url}"]

[[handlers]]
name = "Generic HTTP Downloader"
pattern = "https?://"
command = ["curl", "{url}", "-o", "{outputDir}"]

[[handlers]]
name = "Generic FTP Downloader"
pattern = "ftp://"
command = ["wget", "{url}"]
