name: Build dwnldr Binary

on:
  push:
    branches:
      - main # Trigger build when pushing to the main branch
  pull_request:
    branches:
      - main # Trigger build for pull requests to main

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-mod-

      - name: Install dependencies
        run: go mod tidy # Ensures dependencies are up-to-date

      - name: Build the binary
        run: go build -o dwnldr ./cmd/dwnldr # Builds the binary for the `dwnldr` tool

      - name: Upload the binary as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dwnldr
          path: ./dwnldr # Upload the generated binary as an artifact

